services:
  redis:
    image: redis
    container_name: redisLocal
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - .:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--save", "30", "1", "--loglevel", "warning"]
